#spring:
#  application:
#    name: product-service
#  datasource:
#    url: jdbc:mysql://localhost:3307/product_service_db
#    driver-class-name: com.mysql.cj.jdbc.Driver
#    username: root
#    password: 123qwe
#  jpa:
#    hibernate:
#      ddl-auto: update
#    show-sql: true
#    properties:
#      hibernate:
#        format_sql: true
#
#server:
#  port: 8082


spring:
  config:
    import: "configserver:http://localhost:8888"
  application:
    name: product-service
  profiles:
    active: dev
